# Generated by Django 3.0.7 on 2020-11-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, help_text='是否显示', verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, help_text='排序', verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, help_text='是否显示', verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, help_text='排序', verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
                'db_table': 'publish',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=32)),
                ('phone', models.CharField(default=None, max_length=11, null=True)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('icon', models.ImageField(default='icon/default.jpg', upload_to='icon')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, help_text='是否显示', verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, help_text='排序', verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('img', models.ImageField(default='img/default.jpg', upload_to='img')),
                ('authors', models.ManyToManyField(related_name='books', to='pimordial_drf.Author')),
                ('publish', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='pimordial_drf.Publish')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=False, help_text='是否显示', verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, help_text='排序', verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('mobile', models.CharField(max_length=11)),
                ('author', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='pimordial_drf.Author')),
            ],
            options={
                'verbose_name': '作者详情',
                'verbose_name_plural': '作者详情',
                'db_table': 'author_detail',
            },
        ),
    ]
