# Generated by Django 3.1.3 on 2020-11-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pimordial_drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='UserInfo',
        ),
    ]
