# Generated by Django 3.1.3 on 2020-11-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pimordial_drf', '0002_auto_20201123_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_show',
        ),
    ]
